# Ansible playbook AWS - install docker on ubuntu (2021)
---
- name: "AWS - Install docker"
  hosts: web
  become: yes
  become_method: sudo

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
    - name: Ansible Update Cache and Upgrade all Packages
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Check if container is running
      shell: docker ps

   # - name: run docker image
    # docker run -dit --name repo-name -p 3000:3000 repo-user-name/repo-name:tag
    #  shell: docker run -dit --name snd-portfolio -p 3000:3000 surelay/snd-portfolio:latest

    - name: Sleep for 60 seconds and timeout
      tags: sleep60
      wait_for:
        delay: 60
        timeout: 0

    - name: run docker image
    # docker run -dit --name repo-name -p 3000:3000 repo-user-name/repo-name:tag
      shell: docker run -dit --name snd-portfolio -p 3000:3000 surelay/snd-portfolio:latest
    # shell: docker run -t -i -p 3000:3000 surelay/snd-portfolio:latest 
      
    - name: show running images
      shell: docker images